/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dic.src;

import com.towel.el.annotation.AnnotationResolver;
import com.towel.swing.table.ObjectTableModel;
import java.awt.event.KeyEvent;

import java.util.List;

import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

public class JIFrameSeachMyDictionary extends javax.swing.JInternalFrame {

    public static JIFrameSeachMyDictionary painelPesquisa;
    dic.src.DicionarioWSService service;
    dic.src.DicionarioWS port;
    AnnotationResolver resolver;
    ShowDefine show;
    ObjectTableModel<Definicao> tableModel;

    public JIFrameSeachMyDictionary() {

        initComponents();
        resolver = new AnnotationResolver(Definicao.class);
        tableModel = new ObjectTableModel<Definicao>(
                resolver, "palavra,definicao");
        service = new dic.src.DicionarioWSService();
        port = service.getDicionarioWSPort();

        carregarTabela();
        setTitle("Pesquisa My Dictionary");
        setDefaultCloseOperation(JInternalFrame.HIDE_ON_CLOSE);
        setClosable(true);

    }

    public static JIFrameSeachMyDictionary getInstance() {
        if (painelPesquisa == null) {
            painelPesquisa = new JIFrameSeachMyDictionary();
        }
        return painelPesquisa;
    }

    public void carregarTabela() {

        //Here we use the list to be the data of the table.
        tableModel.setData(getData());
        tabelaDefinicoes.setModel(tableModel);
    }

    //Just for create a default List to show.
    private List<Definicao> getData() {
        return port.listarTodasDefinicoesBD();

    }

    private void aoApertarEnterNoCampoDeLocalizar() {

        if (!campoLocalizar.getText().equals("")) {
            List<Definicao> lista = port.buscarDefinicaoMyDictionary(campoLocalizar.getText());
            tableModel.setData(lista);
            tabelaDefinicoes.updateUI();

        } else {

            carregarTabela();
        }

    }

    public void aoSelecionarItemNaTabela() {
        int index = tabelaDefinicoes.getSelectedRow();
        Definicao obj = tableModel.getValue(index);
        show = new ShowDefine(obj);

        show.setVisible(true);
        show.myDictionary();
        show.setAlwaysOnTop(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        campoLocalizar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaDefinicoes = new javax.swing.JTable();
        btBuscar = new javax.swing.JButton();

        jLabel1.setText("Palavra");

        campoLocalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoLocalizarActionPerformed(evt);
            }
        });
        campoLocalizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoLocalizarKeyReleased(evt);
            }
        });

        tabelaDefinicoes.setBackground(new java.awt.Color(170, 185, 207));
        tabelaDefinicoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaDefinicoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabelaDefinicoesMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaDefinicoes);

        btBuscar.setText("Buscar");
        btBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btBuscarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoLocalizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btBuscar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoLocalizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoLocalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoLocalizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoLocalizarActionPerformed

    private void campoLocalizarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoLocalizarKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            aoApertarEnterNoCampoDeLocalizar();
        }
    }//GEN-LAST:event_campoLocalizarKeyReleased

    private void tabelaDefinicoesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaDefinicoesMousePressed
        if (evt.getClickCount() == 2) {
            aoSelecionarItemNaTabela();
        }

    }//GEN-LAST:event_tabelaDefinicoesMousePressed

    private void btBuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btBuscarMousePressed
        aoApertarEnterNoCampoDeLocalizar();
    }//GEN-LAST:event_btBuscarMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JTextField campoLocalizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaDefinicoes;
    // End of variables declaration//GEN-END:variables

}
