/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dic.src;

import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author NVIDIA
 */
public class ShowDefine extends javax.swing.JFrame {

    /**
     * Creates new form ShowDefine
     */
    Definicao definicao;

    public ShowDefine(Definicao def) {
        definicao = def;
        initComponents();

        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        labelDefinicao.setText("Definicão da palavra: " + def.palavra);
        campoDefinicao.setEditable(false);

        campoDefinicao.setText(def.getDefinicao());
    }

    public void myDictionary() {
        btSalvar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        campoDefinicao = new javax.swing.JTextArea();
        btSalvar = new javax.swing.JButton();
        labelDefinicao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        campoDefinicao.setColumns(20);
        campoDefinicao.setRows(5);
        jScrollPane1.setViewportView(campoDefinicao);

        btSalvar.setText("Salvar Definição");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                    .addComponent(btSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelDefinicao)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(labelDefinicao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        dic.src.DicionarioWSService service = new dic.src.DicionarioWSService();
        dic.src.DicionarioWS port = service.getDicionarioWSPort();
        try {
            port.addDefinicaoBD(definicao);
            JOptionPane.showMessageDialog(rootPane, "Definicão Salva com Sucesso");
            dispose();
        } catch (Exception err) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao salvar a Mensagem" + err.getMessage());
        }

    }//GEN-LAST:event_btSalvarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSalvar;
    private javax.swing.JTextArea campoDefinicao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelDefinicao;
    // End of variables declaration//GEN-END:variables

}
